const Types = {
  LOCATION_FETCH: 'LOCATION/FETCH',
  LOCATION_FETCH_REQUEST: 'LOCATION/FETCH/REQUEST',
  LOCATION_FETCH_SUCCESS: 'LOCATION/FETCH/SUCCESS',
  LOCATION_FETCH_FAILURE: 'LOCATION/FETCH/FAILURE',
}

export default Types
